=== Endlesscrafter/SAXToRDB/artikelliste.dtd
<!ELEMENT artikelliste (ARTIKEL+)>
<!ELEMENT ARTIKEL (artbez,mge,preis,steu,edat)> 
<!ELEMENT artbez (#PCDATA)>
<!ELEMENT mge (#PCDATA)>
<!ELEMENT preis (#PCDATA)>
<!ELEMENT steu (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ATTLIST artbez DT CDATA #REQUIRED>
<!ATTLIST mge DT CDATA #REQUIRED>
<!ATTLIST preis DT CDATA #REQUIRED>
<!ATTLIST steu DT CDATA #REQUIRED>
<!ATTLIST edat DT CDATA #REQUIRED>

=== Endlesscrafter/SAXToRDB/ARTIKEL.XML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE artikelliste SYSTEM "artikelliste.dtd">
<artikelliste>
  <ARTIKEL>
    <artbez DT="varchar(30)">Banane</artbez>
    <mge DT="varchar(5)">kg</mge>
    <preis DT="decimal(12,2)">5.99</preis>
    <steu DT="integer">7</steu>
    <edat DT="date">02.04.2018</edat>
  </ARTIKEL>
  <ARTIKEL>
    <artbez DT="varchar(30)">Bier</artbez>
    <mge DT="varchar(5)">L</mge>
    <preis DT="decimal(12,2)">0.99</preis>
    <steu DT="integer">19</steu>
    <edat DT="date">02.04.2018</edat>
  </ARTIKEL>
</artikelliste>
